name: dart_ml
description: A Dart package to leverage your apps by introducing Machine Learning to it.
version: 0.0.6
homepage: https://github.com/dev-Roshan-lab/dart-ml


environment:
  sdk: ">=2.12.0 <3.0.0"
